apiVersion: batch/v1
kind: CronJob
metadata:
  name: discord-alerts-cron
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: discord-alerts
            image: yourname/cronapp:latest
            ports:
              - containerPort: 3000
            env:
              - name: DISCORD_WEBHOOK_URL
                value: "YOUR_URL"
          restartPolicy: OnFailure
